### ISSUE TITLE
Ubuntu 14.04 LTS 64位 Python2.7.9下 生成结果错误

### ISSUE THREAD

**Issue by Cnly** [ninehills/huami-cli#1]
Key: `123`
Password: `123123`
结果：`A658f6eebB1F167F`
官网结果：`d9Be6f0e833709fe`

请求检查与修复
如果需要其它信息可以联系我

**Comment by ninehills** [comment]
我检查了下，算法没有问题。可能是你对KEY和PASSWORD理解有误：

http://flowerpassword.com/app/web

这个页面中的「记忆密码」指的是Password，也就是123123，
「区分代号」指的是Key，也就是123

这样的话，这个程序和官网的输出是一样的。同时这个记忆密码我这里是做了特殊处理的，必须用Python的getpass模块来获取，避免泄漏。使用时也请设置复杂一点的，同时不要在任何地方使用该记忆密码。

**Comment by ninehills** [comment]
另外补充一个使用的tips：为了防止这个软件的官网被人入侵，从而挂载上记录我的记忆密码的木马，我都是自己把那个页面拔下来，然后扔到自己的server上用的。。

因为本质上这个是个本地计算的程序：http://huami.ninehills.info/

**Comment by Cnly** [comment]
问题已解决。感谢。
